platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 12.0-jdk

inputs:
  - name: spring-boot-hello-repo

run:
  path: "spring-boot-hello-repo/gradlew"
  args: ["--build-file", "spring-boot-hello-repo/build.gradle", "build"]

params:
  TERM: -dumb
  GRADLE_OPTS: -Dorg.gradle.native=false